/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import com.sun.javafx.print.Units;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import logica.Fabrica;
import logica.clases.Artista;
import logica.clases.Espectaculo;
import logica.clases.Funcion;
import logica.interfaces.InterfacePlataforma;

/**
 *
 * @author 59892
 */
public class Alta_funcion_espectaculo extends javax.swing.JFrame {
    ArrayList<String> listaArtistas = new ArrayList<>();
     ArrayList<String> listaEspectaculos = new ArrayList<>();

    private InterfacePlataforma ICU;
    DefaultListModel artistas = new DefaultListModel();

    /**
     * Creates new form Alta_funcion_espectaculo
     */
    public Alta_funcion_espectaculo() {

        initComponents();

        lista_artistas_invitados.setModel(artistas);
        this.ICU = Fabrica.getInstance().getInstanceControladorPlataforma();

        ArrayList<Artista> aartistas = Fabrica.getInstance().getInstanceControladorPlataforma().obtener_artistas_disponibles();
        for (int i = 0; i < aartistas.size(); i++) {
            combobox_artistas.addItem(aartistas.get(i).getNickname());
        }
        ArrayList<String> plataformas = Fabrica.getInstance().getInstanceControladorEspectaculo().obtener_plataformas_disponibles();

        plataformas.forEach((plataforma) -> {
            combobox_plataformas.addItem(plataforma);
        });
        
        jDateFechaRegistro.setDate(new java.util.Date());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        combobox_plataformas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_espectaculos = new javax.swing.JList<>();
        txtNombre = new javax.swing.JTextField();
        combobox_artistas = new javax.swing.JComboBox<>();
        jDateFechaFuncion = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateFechaRegistro = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_artistas_invitados = new javax.swing.JList<>();
        txtHora = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnSubirFuncion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de Funcion en  Espectaculo");

        combobox_plataformas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobox_plataformasItemStateChanged(evt);
            }
        });
        combobox_plataformas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_plataformasActionPerformed(evt);
            }
        });

        jLabel1.setText("Plataforma");

        jScrollPane1.setViewportView(lista_espectaculos);

        combobox_artistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_artistasActionPerformed(evt);
            }
        });

        jDateFechaFuncion.setDateFormatString("yyyy-MM-dd");

        jLabel2.setText("Nombre de funcion");

        jLabel3.setText("Fecha de funcion");

        jDateFechaRegistro.setDateFormatString("yyyy-MM-dd");

        jLabel4.setText("Fecha de ingreso de funcion");

        jScrollPane3.setViewportView(lista_artistas_invitados);

        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });

        jLabel5.setText("Hora de inicio");

        btnAgregar.setText("Sumar artista");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnSubirFuncion.setText("Subir Funcion");
        btnSubirFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirFuncionActionPerformed(evt);
            }
        });

        jLabel6.setText("Artistas invitados");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jButton1.setText("Ver funciones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combobox_plataformas, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDateFechaRegistro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jDateFechaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(combobox_artistas, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(btnAgregar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSubirFuncion)
                                    .addComponent(btnCancelar)
                                    .addComponent(jButton1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combobox_plataformas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateFechaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combobox_artistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubirFuncion)
                        .addGap(23, 23, 23)
                        .addComponent(btnCancelar)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void combobox_plataformasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_plataformasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_plataformasActionPerformed

    private void combobox_plataformasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobox_plataformasItemStateChanged
        String item = (String) combobox_plataformas.getSelectedItem();
        if (item != prev_plataformas_item && item != null) {
//            System.out.println(item);
            prev_plataformas_item = item;

            ArrayList<Espectaculo> espectaculos = Fabrica.getInstance().getInstanceControladorEspectaculo().obtener_espectaculos_con_plataforma(item);
            ArrayList<String> lista = new ArrayList<>();
            espectaculos.forEach((espectaculo) -> {
            lista.add(espectaculo.getId()+"-"+espectaculo.getNombre()+"-"+espectaculo.getPlataforma());
            });

            lista_espectaculos.setListData((String[]) lista.toArray(new String[lista.size()]));
        }
    }//GEN-LAST:event_combobox_plataformasItemStateChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        String artistas_agregados = combobox_artistas.getSelectedItem().toString();
        boolean existe = listaArtistas.contains(artistas_agregados);
        if(!existe){
        listaArtistas.add(artistas_agregados);
        artistas.addElement(artistas_agregados);
        JOptionPane.showMessageDialog(null, "El artista se agrego a la lista");
        }else{
            JOptionPane.showMessageDialog(null, "El artista ya se encuentra en la lista");
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void combobox_artistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_artistasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_artistasActionPerformed

    private void btnSubirFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirFuncionActionPerformed

        if (jDateFechaFuncion.getCalendar() == null) {
            JOptionPane.showMessageDialog(this, "La fecha de la funcion no tiene un formato valido");
            return;
        }
        if (jDateFechaRegistro.getCalendar() == null) {
            JOptionPane.showMessageDialog(this, "La fecha de registro de funcion no tiene un formato valido");
            return;
        }
        if (lista_espectaculos.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this, "No se ha selecciona espectaculo");
            return;
        }
        
        int hora_inicio = -1;
        try {
            hora_inicio=Integer.parseInt(txtHora.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La hora de inicio debe ser un numero");
            return;
        }
        if (hora_inicio < 0 || hora_inicio > 23) {
            JOptionPane.showMessageDialog(this, "La hora de inicio debe ser un numero entre 0 y 23 incluyente");
            return;
        }
        
        String Nombre = txtNombre.getText();
        if (Nombre.length() == 0) {
            JOptionPane.showMessageDialog(this, "Debe especificarse un nombre para la nueva funcion");
            return;
        }
        String fecha_funcion= ((JTextField) jDateFechaFuncion.getDateEditor().getUiComponent()).getText();

        String fecha_registro= ((JTextField) jDateFechaRegistro.getDateEditor().getUiComponent()).getText();
        int id_espectaculo = this.ICU.ExtraerIdDeCombo(lista_espectaculos.getSelectedValue());
        
        Funcion funcion = new Funcion(Nombre, Date.valueOf(fecha_funcion), hora_inicio,Date.valueOf(fecha_registro), id_espectaculo);
        String nombre_Plataforma = combobox_plataformas.getSelectedItem().toString();
// String plataforma = combobox_plataformas.getSelectedItem().toString();
        
      //  Espectaculo es = new Espectaculo(plataforma,correo,nombre,duracion,min_espectadores,max_espectadores,url,costo,Date.valueOf(fecha), idArtista);
     if (this.ICU.Alta_de_Funcion(funcion)){
               int idfuncion = this.ICU.obtener_idfuncion(Nombre);
      for (int i = 0; i<listaArtistas.size(); i++){
          String artista = listaArtistas.get(i);
          int idartista = this.ICU.obtener_idartista(artista);
          this.ICU.insertar_Artista_Invitado(idartista, idfuncion);
      }
      JOptionPane.showMessageDialog(this, "Funcion creada correctamente");
     }
     else {
         JOptionPane.showMessageDialog(null, "Ya existe una funcion con ese Nombre");
     }

       
    }//GEN-LAST:event_btnSubirFuncionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ConsultaFuncionEspectaculo().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alta_funcion_espectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alta_funcion_espectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alta_funcion_espectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alta_funcion_espectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alta_funcion_espectaculo().setVisible(true);
            }
        });
    }
    private String prev_espectaculos_item;
    private String prev_plataformas_item;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSubirFuncion;
    private javax.swing.JComboBox<String> combobox_artistas;
    private javax.swing.JComboBox<String> combobox_plataformas;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateFechaFuncion;
    private com.toedter.calendar.JDateChooser jDateFechaRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> lista_artistas_invitados;
    private javax.swing.JList<String> lista_espectaculos;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
