/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import logica.Fabrica;
import logica.clases.Espectaculo;
import logica.clases.Paquete;
import logica.interfaces.InterfacePlataforma;

/**
 *
 * @author 59892
 */
public class Consulta_paquete_espectaculo extends javax.swing.JFrame {
 ArrayList<Paquete> listaPaquetes = new ArrayList<>();
            //ArrayList<Espectaculo> listaEspectaculo = new ArrayList<>();
            private InterfacePlataforma ICU;
            DefaultListModel paquetes = new DefaultListModel();
           // DefaultListModel espectaculo = new DefaultListModel();
    /**
     * Creates new form Consulta_paquete_espectaculo
     */
    public Consulta_paquete_espectaculo() {
        initComponents();
        this.ICU = Fabrica.getInstance().getInstanceControladorPlataforma();
        listaPaquetes = Fabrica.getInstance().getInstanceControladorPlataforma().obtener_paquetes();
        ArrayList<String> listap = new ArrayList<>();
         listaPaquetes.forEach((paquete) -> {
                listap.add(paquete.getNombre());
            });
         lista_paquetes_registrados.setListData((String[]) listap.toArray(new String[listap.size()]));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista_paquetes_registrados = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_info_paquete = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_espectaculos_de_paquete = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lista_info_espectaculo = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de paquetes de espectaculos");

        lista_paquetes_registrados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_paquetes_registradosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista_paquetes_registrados);

        jLabel1.setText("Paquetes de espectaculos registrados");

        jScrollPane2.setViewportView(lista_info_paquete);

        jLabel2.setText("Informacion de paquete seleccionado");

        jLabel9.setText("Lista de espectaculos incluidos en el paquete");

        lista_espectaculos_de_paquete.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_espectaculos_de_paqueteValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lista_espectaculos_de_paquete);

        jLabel10.setText("Informacion del espectaculo");

        jScrollPane4.setViewportView(lista_info_espectaculo);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Registrar paquete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel9)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(202, 202, 202)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lista_paquetes_registradosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_paquetes_registradosValueChanged
        String item = (String) lista_paquetes_registrados.getSelectedValue();  
        
        if (item != prev_paquete_item && item != null) {
            prev_paquete_item = item;
             
            int idpaquete = this.ICU.ExtraeridPaquete(item);
            ArrayList <String> espectaculos = this.ICU.obtener_espectaculos_de_paquete(idpaquete);
            Paquete paquete = Fabrica.getInstance().getInstanceControladorPlataforma().obtener_info_paquetes(idpaquete);
            ArrayList<String> lista = new ArrayList<>();
                lista.add("Nombre: "+paquete.getNombre());
                lista.add("Descripcion: "+paquete.getDescripcion());
                lista.add("Fecha de inicio: "+paquete.getFecha_inicio().toString());
                lista.add("Fecha de fin: "+paquete.getFecha_fin().toString());
                String descuento = String.valueOf(paquete.getDescuento());
                lista.add("Descuento: "+descuento);
                String id =  String.valueOf(paquete.getId());
                lista.add("ID: "+id);
                for (int i= 0; i<espectaculos.size(); i++){
                    int idespec = this.ICU.obtener_idespectaculo(espectaculos.get(i));
                            Espectaculo espectaculo = Fabrica.getInstance().getInstanceControladorEspectaculo().obtener_espectaculo(idespec);
                   lista.add("Categorias"+(i+1)+": "+ espectaculo.getCategoria()); 
                }
                
                
            lista_info_paquete.setListData((String[]) lista.toArray(new String[lista.size()]));
            //lista_info_paquete.setListData((String[]) listaCategorias.toArray(new String[listaCategorias.size()]));
            
             
            lista_espectaculos_de_paquete.setListData((String[]) espectaculos.toArray(new String[espectaculos.size()]));
       
        }
    }//GEN-LAST:event_lista_paquetes_registradosValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lista_espectaculos_de_paqueteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_espectaculos_de_paqueteValueChanged
         String item2 = (String) lista_espectaculos_de_paquete.getSelectedValue();
        if (lista_espectaculos_de_paquete.getSelectedValue()!= null){
        int idespec = this.ICU.obtener_idespectaculo(item2);          
            
        if (item2 != prev_espectaculo_item && item2 != null) {
            prev_espectaculo_item = item2;
            Espectaculo espectaculo = Fabrica.getInstance().getInstanceControladorEspectaculo().obtener_espectaculo(idespec);
            
            ArrayList<String> listaEspectaculos = new ArrayList<>();
               listaEspectaculos.add("Nombre: "+espectaculo.getNombre());
                listaEspectaculos.add("Descripcion: "+espectaculo.getDescripcion());
                String duracion = String.valueOf(espectaculo.getDuracion());//duracion convertida a string
                listaEspectaculos.add("Duracion: "+duracion);
                String min_espectadores = String.valueOf(espectaculo.getMin_espectador());//minimo de espectadores
                listaEspectaculos.add("Minimo de espectadores: "+min_espectadores);
                String max_espectadores = String.valueOf(espectaculo.getMax_espectador());//maximo de espectadores
                listaEspectaculos.add("Maximo de escpectadores: "+max_espectadores);
                listaEspectaculos.add("URL: "+espectaculo.getUrl());
                String costo = String.valueOf(espectaculo.getCosto());//costo
                listaEspectaculos.add("Costo: "+costo);
                listaEspectaculos.add("Fecha de registro: "+espectaculo.getFecha_registro().toString());
                listaEspectaculos.add("Categoria: "+espectaculo.getCategoria());
                String idPlataforma = String.valueOf(espectaculo.getPlataforma());//id de Plataforma
                listaEspectaculos.add("Plataforma: "+idPlataforma);
               
                
            lista_info_espectaculo.setListData((String[]) listaEspectaculos.toArray(new String[listaEspectaculos.size()]));
            
            }
        }
    }//GEN-LAST:event_lista_espectaculos_de_paqueteValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new RegistraPaquete(getTitle()).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta_paquete_espectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta_paquete_espectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta_paquete_espectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta_paquete_espectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta_paquete_espectaculo().setVisible(true);
            }
        });
    }
    private ArrayList<String> listaCategorias = new ArrayList<>();
    private String prev_paquete_item;
    private String prev_espectaculo_item;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> lista_espectaculos_de_paquete;
    private javax.swing.JList<String> lista_info_espectaculo;
    private javax.swing.JList<String> lista_info_paquete;
    private javax.swing.JList<String> lista_paquetes_registrados;
    // End of variables declaration//GEN-END:variables
}
