/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.Fabrica;

/**
 *
 * @author Tomas
 */
public class ModificarUsuarioSeleccion extends javax.swing.JFrame {

    /**
     * Creates new form ModificarUsuarioSeleccion
     */
    public ModificarUsuarioSeleccion(String prefix) {
        initComponents();
        setTitle(prefix + " - " + getTitle());
        
        ArrayList<String> nicknames = Fabrica.getInstance().getInstanceControllerUsuario().obtener_nicknames_de_usuarios();
        lista_usuarios.setListData(nicknames.toArray(new String[nicknames.size()]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista_usuarios = new javax.swing.JList<>();
        button_editar = new javax.swing.JButton();
        button_cancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccione usuario para editar");

        lista_usuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lista_usuarios);

        button_editar.setText("Editar");
        button_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editarActionPerformed(evt);
            }
        });

        button_cancelar.setText("Cancelar");
        button_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelarActionPerformed(evt);
            }
        });

        jButton1.setText("Ver usuarios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_editar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_editar)
                    .addComponent(button_cancelar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_button_cancelarActionPerformed

    private void button_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editarActionPerformed
        if (!lista_usuarios.isSelectionEmpty()) {
            if(Fabrica.getInstance().getInstanceControllerUsuario().chequear_si_nickname_es_de_artista(lista_usuarios.getSelectedValue())) {
                if (ventana_modificar_artista != null && ventana_modificar_artista.isDisplayable())
                    ventana_modificar_artista.dispose();
                if (ventana_modificar_espectador != null && ventana_modificar_espectador.isDisplayable())
                    ventana_modificar_espectador.dispose();
                
                ventana_modificar_artista = new ModificarArtista(this.getTitle(), Fabrica.getInstance().getInstanceControllerUsuario().obtener_artista_de_nickname(lista_usuarios.getSelectedValue()));
                ventana_modificar_artista.setVisible(true);
            }
            else {
                if (ventana_modificar_artista != null && ventana_modificar_artista.isDisplayable())
                    ventana_modificar_artista.dispose();
                if (ventana_modificar_espectador != null && ventana_modificar_espectador.isDisplayable())
                    ventana_modificar_espectador.dispose();

                ventana_modificar_espectador = new ModificarEspectador(this.getTitle(), Fabrica.getInstance().getInstanceControllerUsuario().obtener_espectador_de_nickname(lista_usuarios.getSelectedValue()));
                ventana_modificar_espectador.setVisible(true);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Primero seleccione un usuario a editar");
    }//GEN-LAST:event_button_editarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ConsultaUsuarioSeleccion(getTitle()).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private ModificarEspectador ventana_modificar_espectador;
    private ModificarArtista ventana_modificar_artista;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancelar;
    private javax.swing.JButton button_editar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista_usuarios;
    // End of variables declaration//GEN-END:variables
}
