/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import logica.Fabrica;
import logica.clases.Artista;
import logica.clases.Espectaculo;

/**
 *
 * @author Tomas
 */
public class MostrarDatosArtista extends javax.swing.JFrame {

    /**
     * Creates new form MostrarDatosEspectador
     */
    public MostrarDatosArtista(String prefix, Artista artista) {
        initComponents();
        setTitle(prefix + " - " + getTitle());
        this.artista = artista;
        nickname.setText(artista.getNickname());
        nombre.setText(artista.getNombre());
        apellido.setText(artista.getApellido());
        correo.setText(artista.getCorreo());

        String pattern = "yyyy-MM-dd";
        SimpleDateFormat format = new SimpleDateFormat(pattern);
        fecha_nacimiento.setText(format.format(artista.getNacimiento()));
        
        descripcion.setText(artista.getDescripcion());
        biografia.setText(artista.getBiografia());
        sitio_web.setText(artista.getSitio_web());
        
        espectaculos = Fabrica.getInstance().getInstanceControllerUsuario().obtener_espectaculos_organizados_por_artista(artista.getId());
        ArrayList<String> lista = new ArrayList<>();
        espectaculos.forEach((espectaculo) -> {
            lista.add(espectaculo.getNombre());
        });

        lista_espectaculos.setListData((String[]) lista.toArray(new String[lista.size()]));

        panel_de_espectaculo_no_seleccion.setVisible(true);
        panel_de_espectaculo_datos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nickname = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        fecha_nacimiento = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        biografia = new javax.swing.JTextArea();
        sitio_web = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_espectaculos = new javax.swing.JList<>();
        panel_de_espectaculo = new javax.swing.JLayeredPane();
        panel_de_espectaculo_datos = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        label_nombre_espectaculo = new javax.swing.JLabel();
        label_descripcion_espectaculo = new javax.swing.JLabel();
        label_fecha_registro_espectaculo = new javax.swing.JLabel();
        label_duracion_espectaculo = new javax.swing.JLabel();
        label_datos_del_espectaculo = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        label_min_espectaculo = new javax.swing.JLabel();
        label_max_espectaculo = new javax.swing.JLabel();
        label_url_espectaculo = new javax.swing.JLabel();
        label_costo_espectaculo = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        label_plataforma_espectaculo = new javax.swing.JLabel();
        panel_de_espectaculo_no_seleccion = new javax.swing.JPanel();
        label_no_datos_funcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Perfil de artista");

        jLabel1.setText("Nickname:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Correo:");

        jLabel5.setText("Fecha de nacimiento:");

        nickname.setText("nickname");

        nombre.setText("nombre");

        apellido.setText("apellido");

        correo.setText("correo");

        fecha_nacimiento.setText("fecha_nacimiento");

        jLabel11.setText("Espectaculos de los que es organizador:");

        jLabel6.setText("Descripcion:");

        descripcion.setText("descripcion");

        jLabel7.setText("Biografia:");

        jLabel8.setText("Sitio web:");

        biografia.setEditable(false);
        biografia.setColumns(20);
        biografia.setRows(5);
        jScrollPane2.setViewportView(biografia);

        sitio_web.setText("sitio_web");

        lista_espectaculos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista_espectaculos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_espectaculosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lista_espectaculos);

        panel_de_espectaculo_datos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel22.setText("Nombre:");

        jLabel23.setText("Descripción:");

        jLabel24.setText("Duración en minutos");

        jLabel25.setText("Fecha en la que se registró:");

        label_nombre_espectaculo.setText("nombre");

        label_descripcion_espectaculo.setText("descripcion");

        label_fecha_registro_espectaculo.setText("fecha_registro");

        label_duracion_espectaculo.setText("duracion");

        label_datos_del_espectaculo.setText("Datos del espectáculo:");

        jLabel26.setText("Espectadores mínimos:");

        jLabel27.setText("Espectadores máximos:");

        jLabel28.setText("Url:");

        jLabel29.setText("Costo:");

        label_min_espectaculo.setText("min");

        label_max_espectaculo.setText("max");

        label_url_espectaculo.setText("url");

        label_costo_espectaculo.setText("costo");

        jLabel30.setText("Plataforma:");

        label_plataforma_espectaculo.setText("plataforma");

        javax.swing.GroupLayout panel_de_espectaculo_datosLayout = new javax.swing.GroupLayout(panel_de_espectaculo_datos);
        panel_de_espectaculo_datos.setLayout(panel_de_espectaculo_datosLayout);
        panel_de_espectaculo_datosLayout.setHorizontalGroup(
            panel_de_espectaculo_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_de_espectaculo_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_de_espectaculo_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_de_espectaculo_datosLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_fecha_registro_espectaculo)
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addComponent(label_datos_del_espectaculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_de_espectaculo_datosLayout.createSequentialGroup()
                        .addGroup(panel_de_espectaculo_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_de_espectaculo_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nombre_espectaculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_descripcion_espectaculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_duracion_espectaculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_min_espectaculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_max_espectaculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_url_espectaculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_costo_espectaculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_plataforma_espectaculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panel_de_espectaculo_datosLayout.setVerticalGroup(
            panel_de_espectaculo_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_de_espectaculo_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_datos_del_espectaculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_de_espectaculo_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(label_nombre_espectaculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_de_espectaculo_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(label_descripcion_espectaculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_de_espectaculo_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_duracion_espectaculo)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_de_espectaculo_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(label_min_espectaculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_de_espectaculo_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(label_max_espectaculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_de_espectaculo_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(label_url_espectaculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_de_espectaculo_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(label_costo_espectaculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_de_espectaculo_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(label_plataforma_espectaculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(panel_de_espectaculo_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(label_fecha_registro_espectaculo))
                .addContainerGap())
        );

        label_no_datos_funcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_no_datos_funcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_no_datos_funcion.setText("[No se ha seleccionado espectáculo]");

        javax.swing.GroupLayout panel_de_espectaculo_no_seleccionLayout = new javax.swing.GroupLayout(panel_de_espectaculo_no_seleccion);
        panel_de_espectaculo_no_seleccion.setLayout(panel_de_espectaculo_no_seleccionLayout);
        panel_de_espectaculo_no_seleccionLayout.setHorizontalGroup(
            panel_de_espectaculo_no_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
            .addGroup(panel_de_espectaculo_no_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(label_no_datos_funcion, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
        );
        panel_de_espectaculo_no_seleccionLayout.setVerticalGroup(
            panel_de_espectaculo_no_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
            .addGroup(panel_de_espectaculo_no_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(label_no_datos_funcion, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
        );

        panel_de_espectaculo.setLayer(panel_de_espectaculo_datos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel_de_espectaculo.setLayer(panel_de_espectaculo_no_seleccion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panel_de_espectaculoLayout = new javax.swing.GroupLayout(panel_de_espectaculo);
        panel_de_espectaculo.setLayout(panel_de_espectaculoLayout);
        panel_de_espectaculoLayout.setHorizontalGroup(
            panel_de_espectaculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_de_espectaculo_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_de_espectaculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_de_espectaculo_no_seleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_de_espectaculoLayout.setVerticalGroup(
            panel_de_espectaculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_de_espectaculo_datos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_de_espectaculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_de_espectaculo_no_seleccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sitio_web))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nickname))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(apellido))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(correo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fecha_nacimiento))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descripcion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(0, 309, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(405, Short.MAX_VALUE)
                    .addComponent(panel_de_espectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nickname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(apellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(correo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fecha_nacimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(descripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sitio_web)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(258, Short.MAX_VALUE)
                    .addComponent(panel_de_espectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lista_espectaculosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_espectaculosValueChanged
        String item = (String) lista_espectaculos.getSelectedValue();
        if (item != prev_esspectaculos_item && item != null) {
            System.out.println(item);
            prev_esspectaculos_item = item;
            
            panel_de_espectaculo_no_seleccion.setVisible(false);
            panel_de_espectaculo_datos.setVisible(true);
            
            Espectaculo espectaculo = espectaculos.get(lista_espectaculos.getSelectedIndex());
            label_plataforma_espectaculo.setText(espectaculo.getPlataforma());
            label_nombre_espectaculo.setText(espectaculo.getNombre());
            label_descripcion_espectaculo.setText(espectaculo.getDescripcion());
            label_duracion_espectaculo.setText(Integer.toString(espectaculo.getDuracion()));
            label_min_espectaculo.setText(Integer.toString(espectaculo.getMin_espectador()));
            label_max_espectaculo.setText(Integer.toString(espectaculo.getMax_espectador()));
            label_url_espectaculo.setText(espectaculo.getUrl());
            label_costo_espectaculo.setText("$" + Integer.toString(espectaculo.getCosto()));
            label_fecha_registro_espectaculo.setText(espectaculo.getFecha_registro().toString());
        }
    }//GEN-LAST:event_lista_espectaculosValueChanged

    private String prev_esspectaculos_item;
    
    private ArrayList<Espectaculo> espectaculos;
    private Artista artista;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido;
    private javax.swing.JTextArea biografia;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel fecha_nacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_costo_espectaculo;
    private javax.swing.JLabel label_datos_del_espectaculo;
    private javax.swing.JLabel label_descripcion_espectaculo;
    private javax.swing.JLabel label_duracion_espectaculo;
    private javax.swing.JLabel label_fecha_registro_espectaculo;
    private javax.swing.JLabel label_max_espectaculo;
    private javax.swing.JLabel label_min_espectaculo;
    private javax.swing.JLabel label_no_datos_funcion;
    private javax.swing.JLabel label_nombre_espectaculo;
    private javax.swing.JLabel label_plataforma_espectaculo;
    private javax.swing.JLabel label_url_espectaculo;
    private javax.swing.JList<String> lista_espectaculos;
    private javax.swing.JLabel nickname;
    private javax.swing.JLabel nombre;
    private javax.swing.JLayeredPane panel_de_espectaculo;
    private javax.swing.JPanel panel_de_espectaculo_datos;
    private javax.swing.JPanel panel_de_espectaculo_no_seleccion;
    private javax.swing.JLabel sitio_web;
    // End of variables declaration//GEN-END:variables
}
