/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import logica.Fabrica;
import logica.clases.Espectador;
import logica.clases.Funcion;

/**
 *
 * @author Tomas
 */
public class MostrarDatosEspectador extends javax.swing.JFrame {

    /**
     * Creates new form MostrarDatosEspectador
     */
    public MostrarDatosEspectador(String prefix, Espectador espectador) {
        initComponents();
        setTitle(prefix + " - " + getTitle());
        this.espectador = espectador;
        nickname.setText(espectador.getNickname());
        nombre.setText(espectador.getNombre());
        apellido.setText(espectador.getApellido());
        correo.setText(espectador.getCorreo());

        String pattern = "yyyy-MM-dd";
        SimpleDateFormat format = new SimpleDateFormat(pattern);
        fecha_nacimiento.setText(format.format(espectador.getNacimiento()));
        
        panel_de_funcion_no_seleccion.setVisible(true);
        panel_de_funcion_datos.setVisible(false);

        funciones = Fabrica.getInstance().getInstanceControllerUsuario().obtener_funciones_a_las_que_se_registro_espectador(espectador.getId());
        ArrayList<String> lista = new ArrayList<>();
        funciones.forEach((funcion) -> {
            lista.add(funcion.getNombre());
        });

        lista_funciones.setListData((String[]) lista.toArray(new String[lista.size()]));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nickname = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        fecha_nacimiento = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_funciones = new javax.swing.JList<>();
        panel_de_funcion = new javax.swing.JLayeredPane();
        panel_de_funcion_datos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label_nombre_funcion = new javax.swing.JLabel();
        label_fecha_funcion = new javax.swing.JLabel();
        label_fecha_registro_funcion = new javax.swing.JLabel();
        label_hora_funcion = new javax.swing.JLabel();
        label_datos_funcion = new javax.swing.JLabel();
        panel_de_funcion_no_seleccion = new javax.swing.JPanel();
        label_no_datos_funcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Perfil de espectador");

        jLabel1.setText("Nickname:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Correo:");

        jLabel5.setText("Fecha de nacimiento:");

        nickname.setText("nickname");

        nombre.setText("nombre");

        apellido.setText("apellido");

        correo.setText("correo");

        fecha_nacimiento.setText("fecha_nacimiento");

        jLabel11.setText("Funciones a las que esta registrado:");

        lista_funciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista_funciones.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_funcionesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lista_funciones);

        panel_de_funcion_datos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel6.setText("Nombre:");

        jLabel7.setText("Fecha:");

        jLabel8.setText("Hora:");

        jLabel9.setText("Fecha en la que se registró:");

        label_nombre_funcion.setText("nombre");

        label_fecha_funcion.setText("fecha");

        label_fecha_registro_funcion.setText("fecha_registro");

        label_hora_funcion.setText("hora");

        label_datos_funcion.setText("Datos de la función:");

        javax.swing.GroupLayout panel_de_funcion_datosLayout = new javax.swing.GroupLayout(panel_de_funcion_datos);
        panel_de_funcion_datos.setLayout(panel_de_funcion_datosLayout);
        panel_de_funcion_datosLayout.setHorizontalGroup(
            panel_de_funcion_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_de_funcion_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_de_funcion_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_de_funcion_datosLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_fecha_registro_funcion)
                        .addGap(0, 79, Short.MAX_VALUE))
                    .addComponent(label_datos_funcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_de_funcion_datosLayout.createSequentialGroup()
                        .addGroup(panel_de_funcion_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(panel_de_funcion_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nombre_funcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_fecha_funcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_hora_funcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panel_de_funcion_datosLayout.setVerticalGroup(
            panel_de_funcion_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_de_funcion_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_datos_funcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_de_funcion_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(label_nombre_funcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_de_funcion_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(label_fecha_funcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_de_funcion_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_hora_funcion)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(panel_de_funcion_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(label_fecha_registro_funcion))
                .addContainerGap())
        );

        label_no_datos_funcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_no_datos_funcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_no_datos_funcion.setText("[No se ha seleccionado función]");

        javax.swing.GroupLayout panel_de_funcion_no_seleccionLayout = new javax.swing.GroupLayout(panel_de_funcion_no_seleccion);
        panel_de_funcion_no_seleccion.setLayout(panel_de_funcion_no_seleccionLayout);
        panel_de_funcion_no_seleccionLayout.setHorizontalGroup(
            panel_de_funcion_no_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
            .addGroup(panel_de_funcion_no_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(label_no_datos_funcion, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
        );
        panel_de_funcion_no_seleccionLayout.setVerticalGroup(
            panel_de_funcion_no_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
            .addGroup(panel_de_funcion_no_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(label_no_datos_funcion, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
        );

        panel_de_funcion.setLayer(panel_de_funcion_datos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel_de_funcion.setLayer(panel_de_funcion_no_seleccion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panel_de_funcionLayout = new javax.swing.GroupLayout(panel_de_funcion);
        panel_de_funcion.setLayout(panel_de_funcionLayout);
        panel_de_funcionLayout.setHorizontalGroup(
            panel_de_funcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_de_funcion_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_de_funcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_de_funcion_no_seleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_de_funcionLayout.setVerticalGroup(
            panel_de_funcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_de_funcion_datos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_de_funcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_de_funcion_no_seleccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nickname))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 463, Short.MAX_VALUE)
                        .addComponent(fecha_nacimiento))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(apellido))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(correo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(350, Short.MAX_VALUE)
                    .addComponent(panel_de_funcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nickname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(apellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(correo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fecha_nacimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(130, Short.MAX_VALUE)
                    .addComponent(panel_de_funcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lista_funcionesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_funcionesValueChanged
        String item = (String) lista_funciones.getSelectedValue();
        if (item != prev_funciones_item && item != null) {
            System.out.println(item);
            prev_funciones_item = item;
            
            panel_de_funcion_no_seleccion.setVisible(false);
            panel_de_funcion_datos.setVisible(true);
            
            Funcion funcion = funciones.get(lista_funciones.getSelectedIndex());
            label_nombre_funcion.setText(funcion.getNombre());
            label_fecha_funcion.setText(funcion.getFecha().toString());
//            label_hora_funcion.setText(toString(funcion.getHora_inicio()));
            int hora = funcion.getHora_inicio();
            label_hora_funcion.setText(Integer.toString(hora));
            label_fecha_registro_funcion.setText(funcion.getFecha_registro().toString());
        }
    }//GEN-LAST:event_lista_funcionesValueChanged

    private String prev_funciones_item;
    private ArrayList<Funcion> funciones;
    private Espectador espectador;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel fecha_nacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_datos_funcion;
    private javax.swing.JLabel label_fecha_funcion;
    private javax.swing.JLabel label_fecha_registro_funcion;
    private javax.swing.JLabel label_hora_funcion;
    private javax.swing.JLabel label_no_datos_funcion;
    private javax.swing.JLabel label_nombre_funcion;
    private javax.swing.JList<String> lista_funciones;
    private javax.swing.JLabel nickname;
    private javax.swing.JLabel nombre;
    private javax.swing.JLayeredPane panel_de_funcion;
    private javax.swing.JPanel panel_de_funcion_datos;
    private javax.swing.JPanel panel_de_funcion_no_seleccion;
    // End of variables declaration//GEN-END:variables
}
