/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.Arrays;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import logica.Fabrica;
import logica.clases.Artista;
import logica.clases.Espectador;

/**
 *
 * @author Tomas
 */
public class RegistraUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistraUsuario
     */
    public RegistraUsuario(String prefix) {
        initComponents();
        this.setTitle(prefix + " - " + this.getTitle());
        
        artista_componentes = new JComponent[] {field_descripcion, field_biografia, field_sitio_web, label_descripcion, label_biografia, label_sitio_web};
        artista_esta_seleccionado = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipo_de_usuario = new javax.swing.ButtonGroup();
        rad_artista = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        field_nickname = new javax.swing.JTextField();
        field_nombre = new javax.swing.JTextField();
        field_apellido = new javax.swing.JTextField();
        field_correo = new javax.swing.JTextField();
        rad_espectador = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        field_biografia = new javax.swing.JTextArea();
        field_sitio_web = new javax.swing.JTextField();
        label_biografia = new javax.swing.JLabel();
        label_descripcion = new javax.swing.JLabel();
        label_sitio_web = new javax.swing.JLabel();
        field_descripcion = new javax.swing.JTextField();
        button_cancelar = new javax.swing.JButton();
        button_registrar = new javax.swing.JButton();
        fecha_nacimiento = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtcontrasenia = new javax.swing.JPasswordField();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de usuario");

        tipo_de_usuario.add(rad_artista);
        rad_artista.setText("Artista");
        rad_artista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_artistaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nickname:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Correo:");

        jLabel5.setText("Fecha de nacimiento:");

        tipo_de_usuario.add(rad_espectador);
        rad_espectador.setSelected(true);
        rad_espectador.setText("Espectador");
        rad_espectador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_espectadorActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo de usuario:");

        field_biografia.setColumns(20);
        field_biografia.setRows(5);
        field_biografia.setEnabled(false);
        jScrollPane1.setViewportView(field_biografia);

        field_sitio_web.setEnabled(false);

        label_biografia.setText("Biografía:");
        label_biografia.setEnabled(false);

        label_descripcion.setText("Descripción:");
        label_descripcion.setEnabled(false);

        label_sitio_web.setText("Sitio web:");
        label_sitio_web.setEnabled(false);

        field_descripcion.setEnabled(false);

        button_cancelar.setText("Cancelar");
        button_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelarActionPerformed(evt);
            }
        });

        button_registrar.setText("Registrar");
        button_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registrarActionPerformed(evt);
            }
        });

        jButton1.setText("Ver usuarios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Contraseña:");

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setText("Click aqui para agregar una imagen");
        imagen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                imagenMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_registrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(44, 44, 44)
                                .addComponent(fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 216, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(label_descripcion)
                            .addComponent(jLabel6)
                            .addComponent(label_biografia)
                            .addComponent(label_sitio_web))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field_sitio_web)
                            .addComponent(jScrollPane1)
                            .addComponent(field_descripcion)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(field_correo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(rad_artista)
                                        .addGap(18, 18, 18)
                                        .addComponent(rad_espectador))
                                    .addComponent(txtcontrasenia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(field_nickname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                    .addComponent(field_nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                    .addComponent(field_apellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(field_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(field_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(field_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(field_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtcontrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rad_artista)
                    .addComponent(rad_espectador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_descripcion)
                    .addComponent(field_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(label_biografia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_sitio_web)
                    .addComponent(field_sitio_web, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_cancelar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_registrar)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rad_artistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_artistaActionPerformed
        Arrays.asList(artista_componentes).forEach((JComponent component) -> {
            component.setEnabled(true);
        });
        artista_esta_seleccionado = true;
        
    }//GEN-LAST:event_rad_artistaActionPerformed

    private void rad_espectadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_espectadorActionPerformed
        Arrays.asList(artista_componentes).forEach((JComponent component) -> {
            component.setEnabled(false);
        });
        artista_esta_seleccionado = false;
    }//GEN-LAST:event_rad_espectadorActionPerformed

    private void button_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_button_cancelarActionPerformed

    private void button_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registrarActionPerformed
        if (field_nickname.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "El nickname del usuario no puede estar en blanco");
            return;
        }
        if (field_nombre.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "El nombre del usuario no puede estar en blanco");
            return;
        }
        if (field_apellido.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "El apellido del usuario no puede estar en blanco");
            return;
        }
        if (field_correo.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "El correo del usuario no puede estar en blanco");
            return;
        }
        if (fecha_nacimiento.getCalendar() == null) {
            JOptionPane.showMessageDialog(this, "La fecha de nacimiento no tiene un formato válido");
            return;
        }
        
        if (fecha_nacimiento.getCalendar() != null) {
            long cant_dias_18_anios = 6574;
            Calendar fecha = fecha_nacimiento.getCalendar();

            // Convertir calendar en LocalDate
            LocalDate fecha_nacimiento_usu = LocalDateTime.ofInstant(fecha.toInstant(), fecha.getTimeZone().toZoneId()).toLocalDate(); 
            LocalDate fechaactual = LocalDate.now();
            long diferencia_en_dias = ChronoUnit.DAYS.between(fecha_nacimiento_usu, fechaactual);

            // Si aca me sobran dias es que le falta para llegar a los 18
            long calculo = diferencia_en_dias - cant_dias_18_anios;
            if (calculo < 0) {
                JOptionPane.showMessageDialog(this, "SOLO SE PERMITEN SUARIOS MAYORES DE EDAD");
                return;
            }
        }
        if (!field_correo.getText().matches(Fabrica.EMAIL_REGEX)) {
            JOptionPane.showMessageDialog(this, "El correo no tiene un formato válido");
            return;
        }
        if (Fabrica.getInstance().getInstanceControllerUsuario().chequear_nickname_repetido(field_nickname.getText())) {
            JOptionPane.showMessageDialog(this, "El nickname ya esta siendo usado por otro usuario");
            return;
        }
        if (Fabrica.getInstance().getInstanceControllerUsuario().chequear_correo_repetido(field_correo.getText())) {
            JOptionPane.showMessageDialog(this, "El correo ya esta siendo usado por otro usuario");
            return;
        }
        if (txtcontrasenia.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "La contraseña del usuario no puede estar en blanco");
            return;
        }
        if (artista_esta_seleccionado) {
            if (field_descripcion.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "La descripción del artista no puede estar en blanco");
                return;
            }
            if (field_sitio_web.getText().length() != 0 && !field_sitio_web.getText().matches(Fabrica.WEB_REGEX)) {
                JOptionPane.showMessageDialog(this, "El sitio web no tiene un formato valido");
                return;
            }
            
            Artista artista = new Artista(field_descripcion.getText(), field_biografia.getText(), field_sitio_web.getText(), field_nickname.getText(), field_nombre.getText(), field_apellido.getText(), field_correo.getText(), fecha_nacimiento.getCalendar().getTime(), -1, new String (txtcontrasenia.getPassword()));
            Fabrica.getInstance().getInstanceControllerUsuario().registrar_artista(artista, imageUsuario);
            JOptionPane.showMessageDialog(this, "Se ha registrado con exito el artista");
        }
        else {
            Espectador espectador = new Espectador(field_nickname.getText(), field_nombre.getText(), field_apellido.getText(), field_correo.getText(), fecha_nacimiento.getCalendar().getTime(), -1, new String (txtcontrasenia.getPassword()));
            Fabrica.getInstance().getInstanceControllerUsuario().registrar_espectador(espectador, imageUsuario);
            JOptionPane.showMessageDialog(this, "Se ha registrado con exito el espectador");
        }
    }//GEN-LAST:event_button_registrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ConsultaUsuarioSeleccion(getTitle()).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void imagenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenMouseReleased
        JFileChooser fileChooser = new JFileChooser();
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            try {
                File file = fileChooser.getSelectedFile();
                imageUsuario = Files.readAllBytes(file.toPath());
                imagen.setIcon(new ImageIcon(new ImageIcon(imageUsuario).getImage().getScaledInstance(imagen.getWidth(), imagen.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                
            } catch (IOException ex) {
                Logger.getLogger(RegistraUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_imagenMouseReleased

    private byte[] imageUsuario; 
    private boolean artista_esta_seleccionado;
    private final JComponent[] artista_componentes;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancelar;
    private javax.swing.JButton button_registrar;
    private com.toedter.calendar.JDateChooser fecha_nacimiento;
    private javax.swing.JTextField field_apellido;
    private javax.swing.JTextArea field_biografia;
    private javax.swing.JTextField field_correo;
    private javax.swing.JTextField field_descripcion;
    private javax.swing.JTextField field_nickname;
    private javax.swing.JTextField field_nombre;
    private javax.swing.JTextField field_sitio_web;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_biografia;
    private javax.swing.JLabel label_descripcion;
    private javax.swing.JLabel label_sitio_web;
    private javax.swing.JRadioButton rad_artista;
    private javax.swing.JRadioButton rad_espectador;
    private javax.swing.ButtonGroup tipo_de_usuario;
    private javax.swing.JPasswordField txtcontrasenia;
    // End of variables declaration//GEN-END:variables
}
